update docs with new config
adrien2p/medusa-plugins pull request #132
Opened 2024-01-08 21:04 UTC by luluhoc

2024-01-09 11:02 UTC, adrien2p requested changes

2024-01-09 11:02 UTC, adrien2p commented on docs/pages/authentication/auth0.mdx
> +                auth0: {
instead, you can directly pass admin/store options at the same level as the identifier/type

2024-01-09 11:03 UTC, adrien2p commented
Thanks a lot for your contribution 💪 greatly appreciated

2024-01-10 08:30 UTC, adrien2p approved these changes
LGTM, they might just be some indentation issues

2024-01-10 11:48 UTC, luluhoc commented
> LGTM, they might just be some indentation issues

fixed indentation issues etc

2024-01-11 09:07 UTC, adrien2p approved these changes

2024-01-11 09:08 UTC, merged